version: '3.8'
services:
  web:
    container_name: web-prod
    build:
      context: ./
      dockerfile: Dockerfile.frontend
      target: production
    volumes:
      - ./apps/frontend/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80
      # - 443:443
    command: nginx -g "daemon off;"

  node:
    container_name: node-prod
    build:
      context: ./
      dockerfile: Dockerfile.backend
      target: production
    ports:
      - 5000:5000
    command: npm run start
